language: php

sudo: false

php:
  - 7.1

    
before_script:
  - travis_retry composer install --prefer-dist --no-interaction
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  
script: 
    - mkdir -p ./build/logs
    - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover ./build/logs/clover.xml;

after_script:
  - php coveralls.phar -v;

matrix:
  include:
    - php: 7.1
      env: coverage=yes
  fast_finish: true  
